export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { StartPage } from './StartPage'
export { HomePage } from './HomePage'
export { NotFoundPage } from './NotFoundPage'
